export const GET_DEVICES = 'GET_DEVICES';
export const DEVICES_ERROR = 'PRODUCTS_ERROR';

export const GET_ORGANIZATIONS = 'GET_ORGANIZATIONS';
export const GET_POSSIBLE_DEPARTMENTS = 'GET_POSSIBLE_DEPARTMENTS';
export const ORGANIZATIONS_ERROR = 'ORGANIZATIONS_ERROR';
export const SET_CURRENT_ORGANIZATION = 'SET_CURRENT_ORGANIZATION';
export const UPDATE_ORGANIZATION = 'UPDATE_ORGANIZATION';
